baseURL = "https://7p7.github.io/"
title = "Central Yharnam"
theme = "hugo-coder"
languagecode = "cn"
hasCJKLanguage = true
defaultcontentlanguage = "zh-cn"
googleAnalytics = "G-3LM3Y0R9NR"
disqusShortname = "7q7"
paginate = 500

[module]
[[module.imports]]
path = "hugo-coder"

[markup.highlight]
style = "solarized-dark"

[params]
author = "7p7"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.jpg"
faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"
since = 2023
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
mode = "auto"
useCDN = true
fuse = true
math = true
useChineseFonts = true

# Menu links
[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2
