baseURL = "https://7p7.github.io/"
title = "Central Yharnam"
theme = "hugo-theme-tokiwa"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
hasCJKLanguage = true
languageCode = "cn"
googleAnalytics = "G-3LM3Y0R9NR"     ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+

disqusShortname = "7q7"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
[params]
mode = "auto"
useCDN = true
fuse = true
math = true
useChineseFonts = true

[module]
[[module.imports]]
path = "hugo-theme-tokiwa"

[menu]
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[outputs]
home = ["HTML", "RSS", "JSON"]
